require:
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rails
  - rubocop-rake
  - rubocop-thread_safety
AllCops:
  NewCops: enable
Layout/LineLength:
  Max: 80
  IgnoredPatterns: ["^ *#"]
Metrics/AbcSize:
  Max: 20
Style/Documentation:
  Enabled: false
